-- =============================================================================
-- requirement_conflicts_seed_group_e.sql -- what the group E rules asset does
-- NOT know, and where two official sources disagree.
--
-- AR, OK, KS, NJ, WV x { MD, APRN }.
--
-- Two kinds of row live here, and both are deliberately left OPEN
-- (resolution = 'unresolved'), which blocks auto-clear (PRD 8.1 condition 6)
-- and raises RULE_UNCERTAIN (PRD 8.3):
--
--   A. GAPS -- a field_key in scope for a state/license_type for which no
--      primary source could be found and read on 2026-09-18. requirement_id is
--      NULL because no requirements row was written. published_value is NULL;
--      notes say what was searched and what remains open.
--
--   B. QUALIFIERS -- a requirements row EXISTS but a second official source, or
--      a statutory exception, narrows or contradicts it. requirement_id points
--      at the row.
--
-- SCOPE NOTE ON requirement_id: the qualifier join below is restricted to rows
-- whose verified_by is 'research-agent-group-e'. This group also found two
-- things that qualify WEST VIRGINIA rows owned by research-agent-group-b
-- (WV/MD/ce_hours_total and WV/MD/ce_topic_controlled_substance_hours). Those
-- are recorded as GAP-shaped rows with requirement_id NULL rather than as
-- foreign keys into another agent's rows, so that re-running either seed file
-- in any order cannot produce a dangling reference or a foreign-key failure.
-- They are no less important for that: one of them says the Board's website and
-- the Board's own legislative rule do not agree.
--
-- observed_by is 'research-agent-group-e' throughout: these are desk-research
-- findings, not observed board behaviour. Rows recording actual board behaviour
-- will be written by delivery (PRD 5.3).
--
-- Run AFTER requirements_seed_group_e.sql. Idempotent.
-- =============================================================================

begin;

delete from requirement_conflicts where observed_by = 'research-agent-group-e';

-- ---------------------------------------------------------------------------
-- B. QUALIFIERS on rows this file wrote.
-- ---------------------------------------------------------------------------
insert into requirement_conflicts
  (requirement_id, published_value, observed_value, observed_at, observed_by,
   occurrences, resolution, notes)
select r.id, c.published_value, c.observed_value,
       timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved', c.notes
from (values

-- ---- ARKANSAS -------------------------------------------------------------
 ('AR','MD','renewal_fee_cents',
  '$11.00, from the Board fee schedule PDF last modified 10 August 2026',
  'the same PDF says the reduction that produced $11 was to "end June 30, 2026"',
  'THE BOARD''S CURRENT FEE SCHEDULE CONTRADICTS ITSELF ON ITS OWN EFFECTIVE PERIOD. The Arkansas State Medical Board fee schedule opens: "Under the authority vested in the Secretary of the Arkansas Department of Health by Act 114 of 2023, the State Medical Board will be reducing certain fees. The fee reduction will be in effect beginning July 1, 2023 and end June 30, 2026 and the reduction may or may not apply in future years." The document was re-published by the Board on 10 August 2026 -- six weeks AFTER the stated end date -- without amendment, and the Board publishes no post-reduction schedule. So either $11 is still what an Arkansas physician pays, or the un-reduced statutory fee has silently resumed and the Board has not said what it is. The seeded value is $11 because that is the only amount the Board publishes. OPEN: ask the Board, or read the un-reduced fee in Ark. Code sec. 17-95-301 et seq. and ASMB Regulation 4. AR/MD/initial_license_fee_cents ($120) carries the identical defect and is covered by this conflict. Source: https://www.armedicalboard.org/Professionals/pdf/Fees.pdf'),

 ('AR','APRN','renewal_fee_cents',
  '$65.00, the APRN certificate renewal fee alone',
  'an Arkansas-RN-holding APRN actually pays $165.00 at each biennial renewal',
  'FEE COMPOSITION. The Arkansas State Board of Nursing fee table footnotes the entire APRN column "* Must also hold a valid RN license", and prices RN renewal separately at $100.00 on the same biennial clock. An APRN whose underlying RN licence is an ARKANSAS RN licence pays $165.00; an APRN whose underlying licence is a COMPACT MULTISTATE RN licence issued by another state pays only the $65.00 seeded here, because the other state collects the RN renewal. The seeded scalar is the advanced credential''s own fee, following the CA/APRN convention in requirements_seed.sql, and is correct for neither population as a total. The same defect applies to AR/APRN/initial_license_fee_cents ($125 APRN original licence; RN licensure $100 by examination or $125 by endorsement; Certificate of Prescriptive Authority a further $160). OPEN: the schema needs a way to express a fee that stacks on a prerequisite credential. Source: https://healthy.arkansas.gov/boards-commissions/boards/nursing-arkansas-state-board/licensing/fees/'),

 ('AR','APRN','ce_hours_total',
  'value_json: 15 contact hours, one of three continuing-education options',
  'a nationally-certified Arkansas APRN may owe ZERO contact hours under this head',
  'The Arkansas State Board of Nursing offers three alternatives -- 15 contact hours, current national certification, or one college credit hour of nursing coursework -- and the Board SEPARATELY requires every renewing APRN to hold "Current National Certification related to your area of certification". The second alternative will therefore be satisfied automatically by essentially the whole APRN population, and the 15-hour figure will rarely bind. A consumer that reads the hours out of the JSON and schedules 15 contact hours every two years for every Arkansas APRN is inventing an obligation. The 5 pharmacotherapeutics hours in AR/APRN/ce_topic_pharmacotherapeutics_hours are NOT an alternative and DO bind on every prescribing APRN. OPEN: confirm with the Board that APRN national certification is accepted as the continuing-education option at renewal. Sources: https://healthy.arkansas.gov/boards-commissions/boards/nursing-arkansas-state-board/education/continuing-education/ and https://healthy.arkansas.gov/boards-commissions/boards/nursing-arkansas-state-board/renewal-of-arkansas-license/aprn-renewal-application-information/'),

 ('AR','APRN','renewal_cycle_months',
  '24 months',
  'a FIRST Arkansas nursing licence runs anywhere from 3 to 27 months',
  'The Arkansas State Board of Nursing states: "The ASBN renews licenses on a staggered biennial birth date system. The first license that is issued may be valid from three (3) months to twenty-seven (27) months depending upon one''s birth date." The seeded 24 is the STEADY-STATE cycle and is wrong for every newly-licensed APRN''s first renewal, by as much as fifteen months in either direction. An obligation generator that dates the first renewal at issuance + 24 months will be wrong for the entire new-licensee cohort. The same staggering exists in several other states in this asset but Arkansas is the only one that publishes the range. OPEN: the schema has no field for a variable first term. Source: https://healthy.arkansas.gov/boards-commissions/boards/nursing-arkansas-state-board/renewal-of-arkansas-license/'),

-- ---- OKLAHOMA -------------------------------------------------------------
 ('OK','MD','ce_cycle_months',
  '36 months',
  'the CE cycle is THREE TIMES the 12-month licence reregistration cycle',
  'This is not an error and must not be "corrected". OAC 435:10-7-10 requires annual reregistration with NO grace period; OAC 435:10-15-1(a)(1)-(2) requires certification "every three years" of "sixty (60) hours of Category I obtained during the preceding three (3) years". Layered on top, OAC 435:10-15-1(a)(4) and 59 O.S. sec. 495a.1(C) impose an ANNUAL 1-hour pain-management/opioid duty on DEA registrants. An Oklahoma physician therefore runs three clocks: a 12-month licence clock anchored to the month of initial licensure, a 36-month CME clock, and a 12-month topic clock -- plus a fourth, the OBN registration expiring 31 October every year. An obligation generator that anchors CME to reregistration will demand 60 hours a year. OPEN: confirm whether the Board audits the 36-month total at every third reregistration or on a rolling lookback. Source: https://www.okmedicalboard.org/download/2501/EFFECTIVE+RULES-MD+Rules_Eff._09.01.2026.pdf'),

 ('OK','MD','csr_renewal_cycle_months',
  '12 months, fixed to 31 October',
  'the licence renews in the physician''s month of initial licensure, not on 31 October',
  'TWO ANNUAL CLOCKS THAT DO NOT COINCIDE. OAC 435:10-7-10 fixes the medical licence to "the month of initial licensure of each individual licensee"; OBN fixes the controlled dangerous substances registration to "October 31st" for everyone, with renewal applications "considered timely only if submitted by September 1st of each year" (OAC 475:10-1-9(e)). A physician licensed in, say, March owes two separate annual filings seven months apart. The requirements table carries interval lengths but no anchor dates, so the platform cannot date either duty from this data alone. OPEN: add a csr_anchor_date / renewal_anchor_date key. Sources: https://www.obndd.ok.gov/registration-pmp/registration and https://www.okmedicalboard.org/download/2501/EFFECTIVE+RULES-MD+Rules_Eff._09.01.2026.pdf'),

 ('OK','APRN','ce_hours_total',
  'value_json: 24 contact hours, one of five continuing-qualification options',
  'OAC 485:10-15-5 imposes NO continuing education hour count on the APRN licence at all',
  'Oklahoma splits the duty across two chapters, the same way Maryland does. OAC 485:10-7-3(d) attaches five alternatives -- 520 work hours, 24 contact hours, current specialty certification, a refresher course, or 6 academic semester credit hours -- to the REGISTERED NURSE licence. OAC 485:10-15-5, which governs APRN renewal, requires only that the nurse''s national certification be current and be maintained, plus the application and fee. A consumer that treats the 24 contact hours as the Oklahoma APRN''s continuing-education obligation is attributing an RN duty to an APRN credential, and is inventing hours for the large majority who satisfy the RN condition by being employed as a nurse or by holding specialty certification. The hours that DO bind on an Oklahoma APRN who prescribes are the 15 pharmacotherapeutics contact hours (or 40 Category I CME hours for independent prescribers) and the 2 pain-management hours, both seeded separately. OPEN: confirm with the Board whether the RN continuing-qualification attestation is audited against APRNs. Source: https://oklahoma.gov/content/dam/ok/en/nursing/documents/485rulesunofficialagencycopy26.pdf'),

 ('OK','APRN','supervision_required',
  'value_json: a supervising physician on file with the Board, for prescribing',
  'no Oklahoma source states a COLLABORATIVE AGREEMENT requirement, and none was seeded',
  'INSTRUMENT DISTINCTION, DELIBERATE. OAC 485:10-16-3(3) and 485:10-16-5(b) require "a written statement from an Oklahoma-licensed physician supervising prescriptive authority" identifying a mechanism for referral, consultation and collaboration and for availability by direct contact or telecommunication. Oklahoma calls this SUPERVISION of prescriptive authority and charges a "$10.00 Supervisory Physician change request" fee for amending it (OAC 485:10-1-3(a)(3)(E)). It is not a collaborative practice agreement of the Arkansas or West Virginia kind, and collaborative_agreement_required was NOT seeded for OK/APRN rather than mapping one instrument onto the other. Note also that the requirement does NOT reach non-prescribing practice: 485:10-16-5(b) conditions it on prescribing "drugs or medical supplies". OPEN: establish whether Oklahoma imposes any condition at all on a non-prescribing APRN. Source: https://oklahoma.gov/content/dam/ok/en/nursing/documents/485rulesunofficialagencycopy26.pdf'),

 ('OK','APRN','renewal_fee_cents',
  '$40.00, the APRN licensure renewal fee alone',
  'an Oklahoma APRN with prescriptive authority and an Oklahoma RN licence pays $155.00',
  'FEE COMPOSITION, same defect as Arkansas and Kansas. OAC 485:10-1-3(a)(2) prices the biennial renewal as separate line items: RN/LPN licence $75.00, APRN licensure $40.00, prescriptive authority $40.00, authority to order/select/obtain/administer drugs $40.00. The seeded scalar is the APRN credential alone. OK/APRN/initial_license_fee_cents ($70) carries the identical defect ($85 prescriptive authority, $85 order-and-administer authority, $85 RN examination). Source: https://oklahoma.gov/content/dam/ok/en/nursing/documents/485rulesunofficialagencycopy26.pdf'),

-- ---- KANSAS ---------------------------------------------------------------
 ('KS','MD','ce_hours_total',
  'value_json: 50 credits over an 18-month lookback (or 100/30 or 150/42)',
  'NONE of the three lookback windows equals the 12-month licence renewal cycle',
  'THE KANSAS PHYSICIAN CE MEASUREMENT PERIOD IS NOT THE RENEWAL PERIOD AND ce_cycle_months WAS DELIBERATELY NOT SEEDED. K.A.R. 100-15-5(a)(1) measures "During the 18-month period immediately preceding the license expiration date" for 50 credits, 30 months for 100, and 42 months for 150, while the Board renews the licence annually. The three options look like a 50-credits-per-year rate with a six-month carry-back, and the 100/30 and 150/42 options look like they exist for licensees renewing after a gap -- but the regulation as published does not say which option applies to whom, and the Board publishes no physician CE explainer page. Seeding ce_cycle_months as 12 (the renewal cycle), as 18 (the shortest lookback), or as anything else would each be an invention. OPEN: read the Board''s CE audit policy, or ask the Board which option a licensee in continuous annual renewal uses. A consumer must not assume 50 credits per 12 months. Sources: http://www.ksbha.org/documents/misc/100-15-5.pdf and https://www.ksbha.ks.gov/departments/licensing/license-fees'),

 ('KS','MD','renewal_window_days',
  '47 days (15 May through 30 June), derived',
  'the Board publishes dates and a late window, not a day count or an expiry date',
  'DERIVATION, NOT PUBLICATION. The Kansas State Board of Healing Arts renewal-dates table gives the MD row as Renewal Cycle "May 15 - July 31" and Late Renewal "July 1 - July 31". 47 = 17 (15-31 May) + 30 (June), on the reading that on-time renewal ends the day before late renewal begins. That reading is supported by K.S.A. 65-2809(d), which gives a licensee 30 days after the renewal date to cure on payment of an additional fee -- the July window -- but the Board does not state the licence expiry date anywhere that could be read, and K.S.A. 65-2809(a) leaves it to regulation ("The license shall be canceled on the date established by rules and regulations of the board which may provide renewal throughout the year on a continuing basis"). OPEN: read K.A.R. 100-15-1 through 100-15-3 for the expiration date. www.ksbha.ks.gov refuses automated clients at the Akamai edge (HTTP 403 to curl with browser headers) and rules.ks.gov, the Kansas Secretary of State''s regulation site, is a JavaScript single-page application whose API returns AccessDenied to unauthenticated requests, so Agency 100 could be read only through the two individual regulation PDFs the Board still hosts on its legacy domain. Source: https://www.ksbha.ks.gov/departments/licensing/renewal-dates'),

 ('KS','MD','renewal_fee_cents',
  'value_json: $360.00 on-line / $430.00 paper',
  'the Board charges two different prices for the same statutory act',
  'NOT A DEFECT IN THE DATA -- a defect in the schema''s assumption that a fee is a scalar. The Kansas State Board of Healing Arts prices the annual physician renewal at "Paper $430.00" and "On-line $360.00", with late surcharges of +$230.00 and +$100.00 respectively. Any consumer that reads a single number here is right for one channel and wrong by $70 for the other. Recorded as value_json. OPEN: the field_key vocabulary should permit value_json for fees by convention, which groups A and E have both now had to do.'),

 ('KS','APRN','collaborative_agreement_required',
  'false',
  'established partly by what K.S.A. 65-1130 does NOT say',
  'READ THIS BEFORE RELYING ON THE FALSE. K.S.A. 65-1130(d)(1), as amended by L. 2022, ch. 65, sec. 1, affirmatively grants an APRN authority to "prescribe durable medical equipment and prescribe, procure and administer any drug consistent with such licensee''s specific role and population focus", and subsection (d)(3) enumerates the ONLY conditions on controlled substances: federal DEA registration and compliance with DEA requirements. No collaborating physician, protocol or supervision condition appears anywhere in the section. The 2022 amendment is the enactment that removed Kansas''s prior protocol requirement, so this is an affirmative grant plus a dated repeal, not bare silence -- but the negative is still established in part by absence, and the revisor''s own case annotations to the section still carry a pre-2022 note beginning "Refusal to enter into a collaborative practice agreement by a hospital or private phys...". OPEN: confirm against K.A.R. 60-11-101 et seq. (the Board of Nursing''s APRN regulations), which could not be read -- rules.ks.gov is a JavaScript application with no server-rendered text and its API rejects unauthenticated requests. A consumer that tells a Kansas APRN no agreement is needed, wrongly, exposes them to unlicensed-practice risk. Source: https://ksrevisor.gov/statutes/chapters/ch65/065_011_0030.html'),

 ('KS','APRN','renewal_fee_cents',
  '$55.00, the APRN licence renewal fee alone',
  'a Kansas APRN holding a Kansas RN licence pays $140.00 and files TWO applications',
  'FEE AND FILING COMPOSITION. The Kansas State Board of Nursing prices "Advanced Practice Registered Nurses (APRNs) [KAR 60-11-119] ... Biennial renewal of license: $55.00" and "Professional Nurses (RNs) [KAR 60-4-101] ... Biennial renewal of license: $85.00". The Board''s Renewal Application page carries a standing notice: "Due to changes made for the NLC, APRNs with Kansas RN licenses must fill out a renewal application for both licenses. Confirm that your cart has all of the licenses that you need to renew when checking out." This is a two-filing, two-fee event that the platform will represent as one. OPEN: model the RN prerequisite as its own credential. Sources: https://ksbn.kansas.gov/fees/ and https://ksbn.kansas.gov/renewal-application/'),

-- ---- NEW JERSEY -----------------------------------------------------------
 ('NJ','MD','renewal_cycle_months',
  '24 months, licences expiring 30 June of odd years',
  'the only retrievable source is a Board presentation dated AUGUST 2017',
  'SOURCE AGE. "The Board of Medical Examiners LICENSING and the APPLICATION PROCESS" is a New Jersey Division of Consumer Affairs document hosted on the Division''s own server, and it is the only New Jersey physician renewal statement that could be retrieved on 2026-09-18. It is nine years old. The biennial odd-year structure it states is a structural feature of N.J.S.A. 45:9-6 registration rather than a periodically re-set parameter, which is why it was seeded while the FEES in the same document ("$580 renewal fee", "$325 application fee", "$225 one time endorsement fee", "Registration fee of $290 per year") were NOT -- a nine-year-old fee is exactly the kind of confidently-wrong value this asset exists to avoid. OPEN: confirm the current cycle and obtain current fees from N.J.A.C. 13:35-6.13 (Fee schedule) or from the Board directly. www.njconsumeraffairs.gov returns an Imperva/Incapsula challenge to every .aspx path (HTTP 403, or a 212-byte _Incapsula_Resource stub on a direct fetch), including /bme/Pages/renewals.aspx, /bme/Pages/FAQ.aspx, /bme/Pages/regulations.aspx and /renewals/Pages/RenewalsTemplateDetails.aspx; New Jersey licenses the N.J.A.C. to LexisNexis and the Office of Administrative Law''s own Access to Rules page states that "the online version of the Code is not the official Code". Source: https://www.njconsumeraffairs.gov/documents/licenseprocess/bme-licensing-august-2017.pdf'),

-- ---- WEST VIRGINIA --------------------------------------------------------
 ('WV','MD','csr_required',
  'value_json with "required": false and "conditionally_required": true',
  'the credential exists and is enforced, but most West Virginia physicians do not need it',
  'A DELIBERATELY QUALIFIED FALSE. The West Virginia Board of Medicine''s Controlled Substance Dispensing Practitioner Registration is required only "To dispense or administer a controlled substance in an office-based setting", "at each office location", and the Board states plainly that it "is not required for: (1) inpatient hospital practice; or (2) to write prescriptions which are to be dispensed by a pharmacy." A bare boolean true would bill a registration to the large majority of West Virginia physicians who only write prescriptions; a bare false would let an office-dispensing physician go unregistered. Hence value_json. SEPARATE AND UNRESOLVED: whether West Virginia ALSO operates a general practitioner controlled-substance licence through the Board of Pharmacy under W. Va. Code ch. 60A. No Board of Pharmacy page was read in this pass, and the absence of one is not evidence. OPEN. Source: https://wvbom.wv.gov/download_resource.asp?id=710'),

 ('WV','APRN','renewal_window_days',
  '61 days (1 May through 30 June), derived',
  'published as dates, not as a day count',
  'DERIVATION, NOT PUBLICATION -- though a well-supported one. The West Virginia Board of Registered Nurses publishes "Advanced Practice (APRN) May 1 - June 30 (Every Odd Year)" and states the open boundary in terms that exclude an earlier date: "official West Virginia renewal windows open strictly on May 1", with a warning that automated e-Notify notices sent on 1 April "are system-generated ... Please disregard early notices until the portal officially opens." 31 + 30 = 61. OPEN: confirm the window is fixed across cycles rather than announced per cycle, and confirm whether any grace period follows 30 June (the Board says only that "Failure to renew by June 30 causes your license to lapse immediately" for RNs). Source: https://wvrnboard.wv.gov/licensing/renewals'),

 ('WV','APRN','renewal_cycle_months',
  '24 months, odd years',
  'the APRN licence can lapse in an EVEN year through the RN licence it depends on',
  'THE MOST DANGEROUS CLOCK IN THIS GROUP. West Virginia renews RNs in EVEN years and APRNs in ODD years, and makes the APRN licence derivative: "Your APRN license depends directly on maintaining an active RN license -- either a West Virginia RN license or an active multistate RN license from a Compact state. If your underlying RN license lapses or becomes invalid, your APRN license and Prescriptive Authority will automatically lapse as well, regardless of the APRN odd-year renewal schedule." A platform that tracks only the APRN''s 24-month odd-year clock will show a West Virginia APRN as compliant through the even year in which their RN licence quietly expires, at which point the APRN licence and prescriptive authority are already gone. The RN prerequisite may also be a COMPACT licence issued by a different state entirely, on that state''s clock. OPEN: model the prerequisite credential. Source: https://wvrnboard.wv.gov/licensing/renewals'),

 ('WV','APRN','ce_topic_controlled_substance_hours',
  'value_json: 3 hours ONE TIME, within 1 year of initial licensure',
  'the Board of Medicine states the analogous physician duty as recurring EVERY reporting period',
  'PERIODICITY ASYMMETRY BETWEEN TWO WEST VIRGINIA BOARDS, AND IT MAY BE REAL. The Board of Registered Nurses scopes the APRN duty to the first year: "If you prescribe, administer, or dispense controlled substances, you must complete 3 hours in drug diversion, best-practice prescribing, and opioid antagonist training within 1 year of initial licensure", and publishes a waiver for a first-year APRN who did not prescribe. The Board of Medicine''s website scopes the physician duty to every cycle: "required to complete 3-hours of Board-approved CME ... during each reporting period. This is not a one-time only requirement." Either West Virginia genuinely holds physicians to a recurring duty and APRNs to a one-time one, or one of the two boards has published an incomplete statement. The nursing row is seeded as one-time because that is what the nursing board says. OPEN: read 19 CSR 8 (the Board of Registered Nurses'' APRN rule) for a periodic controlled-substance CE provision. Sources: https://wvrnboard.wv.gov/education/continuing-education and https://wvbom.wv.gov/Cont_Med_Education.asp'),

 ('WV','MD','ce_topic_nutrition_hours',
  'value_json: 2 hours per reporting period, under every CME option',
  'adopted by EMERGENCY RULE effective 11 August 2026 and absent from the Board''s own CE web page',
  'NEW DUTY, NEW FIELD KEY, AND A BOARD WEBSITE THAT HAS NOT CAUGHT UP. 11 CSR 6, filed 30 June 2026 and effective 11 August 2026 as an EMERGENCY rule with a sunset of 1 August 2032, inserts 2 hours of Nutrition CME into all three physician CME options (secs. 4.1.1.b, 4.1.2.a, 4.1.3.a) and adds a definition of "Nutrition CME" at sec. 2.12. The Board''s Continuing Education - Medical Doctors page -- the source the earlier pass read for WV/MD/ce_hours_total and ce_cycle_months -- does not mention it. TWO CONSEQUENCES A CONSUMER MUST KNOW: (1) the duty is real and current, and a West Virginia physician planning from the Board''s web page will miss it; (2) it is an EMERGENCY rule, which in West Virginia has a limited life and may be modified or allowed to expire before it is made permanent, so the row should be re-verified. Note also that the PDF is a REDLINE of the prior rule and strikethrough text does not survive extraction, so a deleted provision would be invisible. OPEN: confirm the permanent rule when filed. Source: https://wvbom.wv.gov/download_resource.asp?id=904')

) as c(state, license_type, field_key, published_value, observed_value, notes)
join requirements r
  on r.state = c.state
 and r.license_type = c.license_type
 and r.field_key = c.field_key
 and r.is_current
 and r.deleted_at is null
 and r.verified_by = 'research-agent-group-e';

-- ---------------------------------------------------------------------------
-- A. GAPS -- in-scope field_keys with no verified value, and findings that
--    qualify rows owned by another agent. requirement_id NULL throughout.
-- ---------------------------------------------------------------------------
insert into requirement_conflicts
  (requirement_id, published_value, observed_value, observed_at, observed_by,
   occurrences, resolution, notes)
values

-- ---- WV/MD rows owned by research-agent-group-b, qualified from here -------
(null,
 'WV/MD/ce_topic_controlled_substance_hours (research-agent-group-b): 3 hours during EACH two-year reporting period, "not a one-time only requirement"',
 '11 CSR 6 sec. 11-6-3, emergency rule effective 11 August 2026, imposes the 3 hours ONLY "Within one year of receiving an initial license"',
 timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'THE BOARD''S WEBSITE AND THE BOARD''S OWN LEGISLATIVE RULE DO NOT AGREE ON THE PERIODICITY OF A REAL DUTY. wvbom.wv.gov/Cont_Med_Education.asp, the source of the existing seeded row, states: "Physicians who have prescribed, administered, or dispensed any controlled substance pursuant to a West Virginia license in the two-year reporting period preceding renewal, are required to complete 3-hours of Board-approved CME in Risk Assessment and Responsible Prescribing of Controlled Substances Training ... during each reporting period. This is not a one-time only requirement." The Board''s emergency legislative rule 11 CSR 6 (filed 30 June 2026, effective 11 August 2026) has exactly ONE provision on the subject, sec. 3.1, headed "Mandatory Continuing Education Activity for Physicians and Podiatric Physicians Upon Initial Licensure", which requires the 3 hours "Within one year of receiving an initial license ... This requirement is waived for licensees who do not prescribe, administer, or dispense any controlled substances whatsoever pursuant to a West Virginia license." Section 11-6-4 (Periodic Continuing Education) contains no controlled-substance topic at all. IMPORTANT CAVEAT AGAINST OVER-READING THIS: the rule PDF is a redline and struck-through text does not survive PDF text extraction, so a deleted recurring provision would be invisible to this method. NO ROW WAS CHANGED. The existing group-B row stands, because over-scheduling a 3-hour course is a smaller harm than telling a West Virginia prescriber they are finished. OPEN: obtain a clean copy of 11 CSR 6 as filed with the West Virginia Secretary of State, and ask the Board which statement governs. Sources: https://wvbom.wv.gov/download_resource.asp?id=904 and https://wvbom.wv.gov/Cont_Med_Education.asp'),

(null,
 'WV/MD/ce_hours_total (research-agent-group-b): 50 hours',
 '11 CSR 6 sec. 4.1 makes the 50 hours ONE OF THREE alternative options; the other two require no hour count',
 timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'QUALIFIER ON A ROW OWNED BY ANOTHER AGENT. 11 CSR 6 sec. 4.1 (emergency rule effective 11 August 2026) gives West Virginia physicians three ways to satisfy CME: Option 1, "a minimum of 50 hours of continuing medical education designated as Category I by the AMA or the ... AAFP", of which at least 30 must be in the physician''s specialty, at least 2 in Nutrition, and up to 20 may be claimed for teaching or precepting; Option 2, 2 hours of Nutrition CME plus passing an ABMS member board certification or recertification examination during the reporting period, or current successful involvement in an ABMS maintenance-of-certification programme; Option 3, 2 hours of Nutrition CME plus "a minimum of 12 months of an ACGME approved post-graduate training program or fellowship". The rule closes: "There are no other types or categories of continuing medical education satisfactory to the Board for physicians." A board-certified physician engaged in MOC therefore owes 2 hours, not 50. The seeded scalar 50 is correct for Option 1 and over-bills every physician on Options 2 or 3. NO ROW WAS CHANGED because ux_requirements_current permits only one current row per key and the existing row is not wrong, only incomplete. OPEN: re-seed WV/MD/ce_hours_total as value_json carrying the three options. Source: https://wvbom.wv.gov/download_resource.asp?id=904'),

-- ---- ARKANSAS gaps --------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP AR/MD/renewal_window_days. The Arkansas State Medical Board''s physician licensure instructions say "Your first renewal notification will be sent to you via email 60 days prior to the end of your birth month." That is a NOTIFICATION date, not a transactional open date, and the Board states separately that renewal is "available strictly online" with "no grace period". The same defect as the seeded CA/MD, CT/MD and PA/MD figures elsewhere in this asset -- but unlike those, no number was seeded here, because Arkansas gives no second statement to corroborate a transactional reading. NOT SEEDED. Source: https://www.armedicalboard.org/Professionals/pdf/MD_AppPack.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP AR/MD/fingerprint_required and AR/APRN/fingerprint_required. The Arkansas State Medical Board''s licensure instructions state: "Every person applying for a license or renewal of a license issued by the Arkansas State Medical Board shall provide written authorization to the board to allow the Arkansas State Police to release the results of a state and federal criminal history background check report to the Board", and the Board''s fee schedule charges "Criminal Background Check (State & Federal) $36.25". The Arkansas State Board of Nursing publishes a Criminal Background Checks page under Licensing. NEITHER SOURCE USES THE WORD FINGERPRINT. A state-and-federal criminal history check is in practice fingerprint-based, but "in practice" is not verification, and a fingerprint_required boolean asserted from an inference is exactly the kind of row this asset must not contain. NOT SEEDED for either licence type. NOTE ALSO, and separately worth an obligation of its own: the Arkansas medical background-check requirement is stated to apply at RENEWAL as well as at initial licensure, which is unusual -- most states in this asset impose it only at initial licensure. OPEN: read ASMB Regulation on criminal background checks and the ASBN Criminal Background Checks page. Sources: https://www.armedicalboard.org/Professionals/pdf/MD_AppPack.pdf and https://www.armedicalboard.org/Professionals/pdf/Fees.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP AR/MD/csr_required and AR/APRN/csr_required -- AND A NEGATIVE THAT COULD NOT BE ASSERTED. The Arkansas Department of Health''s Controlled Substances page states that "Persons engaged in research on the use and effects of controlled substances, including persons conducting instructional activities, conducting chemical analysis or conducting animal training and animal euthanasia with controlled substances in the course of their practice, must obtain a Controlled Substance Registration Certificate from the State of Arkansas" -- a list that conspicuously does NOT include ordinary prescribing practitioners. The Department''s Rules and Regulations Pertaining to Controlled Substances says instead: "Every Practitioner defined as follows shall obtain a registration from the Federal Drug Enforcement Administration (D.E.A.), Department of Justice, unless exempted by Law", i.e. it points practitioners at the FEDERAL registration. Read together these strongly suggest Arkansas does NOT require a separate state controlled-substance registration of prescribing physicians and APRNs, which would make csr_required false -- but a negative cannot be asserted from a list that merely omits a category, and the Board of Nursing''s own prescriptive authority page says only that "The ASBN Rules require that you submit a copy of your DEA number to the ASBN". NOT SEEDED IN EITHER DIRECTION. OPEN: read Ark. Code sec. 5-64-302 and the Department''s registration application. A false here is worth as much as a true and would save every Arkansas client a filing. Sources: https://healthy.arkansas.gov/programs-services/prevention-healthy-living/pharmacy-services-drug-control/controlled-substances/, https://healthy.arkansas.gov/wp-content/uploads/controlled_substancesRulesRegs.pdf and https://healthy.arkansas.gov/boards-commissions/boards/nursing-arkansas-state-board/advanced-practice/collaborative-practice/'),

-- ---- OKLAHOMA gaps --------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP OK/MD/renewal_window_days and OK/APRN/renewal_window_days. OAC 435:10-7-10 says only that "Reregistration shall be conducted during the month of initial licensure of each individual licensee by the Board" and that "No grace period shall be allowed" -- a calendar month, not an offset, and the rule does not say whether the portal opens before that month. The Board''s Licensing FAQ adds a notice date, not an open date: "the Board does mail renewal notices approximately sixty (60) days prior to the expiration of a license." For the Board of Nursing, no renewal window statement of any kind was found; OAC 485:10-7-3(a) says only that licences "may be renewed in accordance with the schedule published by the Board". NOT SEEDED for either licence type. This is the same schema gap groups A-D recorded: the field is an offset in days and several states publish a fixed calendar month or a pair of dates instead. Sources: https://www.okmedicalboard.org/download/2501/EFFECTIVE+RULES-MD+Rules_Eff._09.01.2026.pdf and https://www.okmedicalboard.org/licensing_faq'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP OK/MD/fingerprint_required and OK/APRN/fingerprint_required. Neither board publishes one. OAC Title 435, read in full as the Board''s rules effective 1 September 2026, contains no occurrence of "fingerprint", "criminal history" or "background check" anywhere in the text. OAC Title 485 was read for fees, renewal and prescriptive authority but not searched exhaustively for a background-check provision. NOT SEEDED. OPEN: 59 O.S. secs. 480-518.1 and 59 O.S. secs. 567.1-567.19.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP OK/MD -- an unrepresentable mandated education duty. OAC 435:10-15-1(a)(5) requires that "Each licensee who is health care provider, an administrator, or chief executive officer associated with an inpatient health care services entity shall observe the online presentation related to medical treatment laws described in subsection A of 63 O.S. sec. 3162 as part of his or her continuing education at least once during each consecutive two-calendar-year period." It is mandatory, it runs on a TWO-CALENDAR-YEAR clock that matches neither the 12-month licence cycle nor the 36-month CME cycle, it applies only to an occupational subset, and IT HAS NO HOUR COUNT. No field_key in the vocabulary can hold it and none was invented for it, because inventing ce_topic_medical_treatment_laws_hours with a null hour count would produce a row that asserts nothing useful. Subsection (a)(6) has the same shape for physicians registered with the Oklahoma Medical Marijuana Authority (63 O.S. sec. 427.10). NOT SEEDED. OPEN: the schema needs a slot for a mandated activity with no duration. Source: https://www.okmedicalboard.org/download/2501/EFFECTIVE+RULES-MD+Rules_Eff._09.01.2026.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'SCOPE GAP, OKLAHOMA: the OK/MD rows come from OAC TITLE 435 and MUST NOT be applied to an Oklahoma DO. Oklahoma has a separate State Board of Osteopathic Examiners with its own title of the Administrative Code (OAC Title 510) and its own fees, reregistration rule and CME requirements, none of which was read in this pass. This is the same hazard groups A and B recorded for Pennsylvania and Michigan. In Arkansas, by contrast, the State Medical Board licenses both and its fee schedule names "M.D./D.O." on one line -- so the AR/MD rows are LIKELY to hold for an Arkansas DO, though no DO-specific page was read and "likely" is not verified. Kansas, New Jersey and West Virginia were not checked for board separation. Source: https://www.armedicalboard.org/Professionals/pdf/Fees.pdf'),

-- ---- KANSAS gaps ----------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP KS/MD/ce_cycle_months -- deliberately not seeded, see the linked qualifier on KS/MD/ce_hours_total. K.A.R. 100-15-5 measures credits over 18, 30 or 42 months preceding the licence expiration date while the licence renews annually, and the regulation does not say which option a continuously-renewing licensee uses. NOT SEEDED: 12 would be the renewal cycle rather than the measurement period, and 18 would assume an option the regulation does not assign. Source: http://www.ksbha.org/documents/misc/100-15-5.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP KS/MD/fingerprint_required, KS/MD/csr_required, KS/APRN/csr_required. The Kansas State Board of Healing Arts publishes no fingerprint or background-check statement that could be read; its own site refuses automated clients at the Akamai edge. On controlled substances, no Kansas source was found in either direction: Kansas''s Uniform Controlled Substances Act (K.S.A. ch. 65 art. 41) assigns registration to the Board of Pharmacy, and whether a licensed practitioner holding a federal DEA registration must also hold a Kansas registration was not established. K.S.A. 65-1130(d)(3), read in full, requires a Kansas APRN to "Register with the federal drug enforcement administration" and to "comply with federal drug enforcement administration requirements related to controlled substances" -- and says nothing about a state registration, which is suggestive but is not an affirmative statement that none exists. NOT SEEDED IN EITHER DIRECTION. OPEN: read K.S.A. 65-4101 et seq. and the Kansas Board of Pharmacy''s registration pages. Source: https://ksrevisor.gov/statutes/chapters/ch65/065_011_0030.html'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP KS/APRN -- the Kansas Board of Nursing''s own regulations (K.A.R. agency 60) could not be read. The Board cites them on every page (K.A.R. 60-4-101 for RN fees, 60-11-119 for APRN fees, 60-3-107 and 60-3-108 for application and renewal dates, 60-9-105 for continuing nursing education), and the seeded KS/APRN rows come from the Board''s own statements of what those regulations require rather than from the regulation text. rules.ks.gov, the Kansas Secretary of State''s official K.A.R. site, is a JavaScript single-page application whose only retrievable routes are /browse, /search and /smart-search and whose API paths return an S3 AccessDenied to unauthenticated requests; sos.ks.gov/publications/pubs_kar.aspx and pubs_kar_Regs.aspx return CloudFront 403. The Board of Healing Arts regulations (agency 100) were retrievable only because that Board still hosts two individual PDFs on its legacy domain ksbha.org, whose TLS certificate has expired -- they were read through a fetcher that does not fail on that. OPEN: K.A.R. 60-3-108 (APRN expiration dates and the odd/even birth-year rule the Board quotes on its Information Center page) and K.A.R. 60-11-101 et seq. (APRN practice, including whether any practice agreement survives the 2022 amendment to K.S.A. 65-1130).'),

-- ---- NEW JERSEY gaps ------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'SOURCE ACCESS FAILURE, NEW JERSEY -- STILL THE THINNEST JURISDICTION IN THE ASSET AFTER THIS PASS. New Jersey now holds seven rows across both licence types (NJ/MD: renewal_cycle_months, csr_required, csr_fee_cents; NJ/APRN: collaborative_agreement_required and initial_license_fee_cents from group A, plus csr_required and csr_fee_cents here). STILL NOT SEEDED for NJ/MD: renewal_window_days, ce_hours_total, ce_cycle_months, every ce_topic, initial_license_fee_cents, renewal_fee_cents, fingerprint_required, csr_renewal_cycle_months. STILL NOT SEEDED for NJ/APRN: renewal_cycle_months, renewal_window_days, ce_hours_total, ce_cycle_months, every ce_topic, renewal_fee_cents, supervision_required, fingerprint_required, csr_renewal_cycle_months. WHAT CHANGED THIS PASS, AND WHAT DID NOT: www.njconsumeraffairs.gov serves PDF ASSETS to automated clients normally -- /documents/licenseprocess/*.pdf, /dcu/Applications/*.pdf and /bme/Applications/*.pdf all returned real PDFs -- while every .aspx page still returns an Imperva/Incapsula challenge (a 212-byte _Incapsula_Resource stub to a direct fetch, HTTP 403 through a fetcher). So New Jersey is reachable for anything the Division has published as a PDF and unreachable for everything it has published as a page. The N.J.A.C. remains licensed to LexisNexis: the Office of Administrative Law''s Access to Rules page directs the public to lexisnexis.com/hottopics/njcode, which redirects to an advance.lexis.com container, and states that "the online version of the Code is not the official Code". N.J.A.C. 13:35-6.13 (BME fee schedule) and 13:35-6.15 (continuing medical education) were therefore NOT read; a 2005-supplement scan of chapter 35 held by the New Jersey State Library''s dspace repository WAS retrieved and read but is twenty-one years old and predates New Jersey''s opioid and cultural-competency CME mandates entirely, so nothing was seeded from it. OPEN: enumerate the Division''s PDF asset paths for a current BME fee or CME notice, or obtain the chapter text by written request. DO NOT LET ANY CONSUMER FALL BACK TO A NEIGHBOURING STATE FOR NEW JERSEY.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP NJ/MD/csr_renewal_cycle_months and NJ/APRN/csr_renewal_cycle_months. The New Jersey Drug Control Unit''s CDS registration application (rev. 4/25) states the $40.00 fee and the fact that "A New Jersey CDS registration is the prerequisite to the federal DEA registration", and the Unit''s registration FAQ repeats $40.00 as the RENEWAL fee for physicians, APNs and CNMs -- but neither document states the LENGTH of the registration term or its expiration date, and the FAQ page explicitly omits it. The application form has blanks for "Effective date" and "Expiration date" to be filled by the Unit. NOT SEEDED. THIS MATTERS MORE IN NEW JERSEY THAN ALMOST ANYWHERE: because the state registration is a prerequisite to the federal DEA registration, letting it lapse takes the DEA registration with it. OPEN: N.J.A.C. 13:45H-1.2 and the Unit''s renewal notice. Sources: https://www.njconsumeraffairs.gov/dcu/Applications/Initial-Application-for-Registration-for-Dispenser-Prescriber-MidLevel-Practitioner.pdf and https://www.njconsumeraffairs.gov/dcu/Pages/FAQregistration.aspx'),

-- ---- WEST VIRGINIA gaps ---------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP WV/MD/renewal_window_days. The West Virginia Board of Medicine publishes the expiration date and the alphabetical cohort rule -- "Regardless of the date of license issuance, A-L physicians renew by June 30th in even years and M-Z physicians renew by June 30th in odd years. Thereafter, all eligible physicians may renew licensure for two-year intervals" -- but no date on which renewal opens. NOT SEEDED. Note the contrast with the sibling board: the Board of Registered Nurses publishes its window as "May 1 - June 30" and states that windows "open strictly on May 1". Carrying the nursing board''s window across to physicians would be inference from a different regulator and was not done. Source: https://wvbom.wv.gov/download_resource.asp?id=686'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'GAP WV/APRN/csr_required. The West Virginia Board of Registered Nurses states on its Prescriptive Authority page: "Prescriptive authority granted by the Board does not automatically permit prescribing controlled substances. To prescribe Schedules II-V, APRNs must separately obtain a federal DEA registration and register with the West Virginia Controlled Substances Monitoring Program (CSMP)." CSMP REGISTRATION IS A PRESCRIPTION-DRUG-MONITORING-PROGRAM ENROLMENT, NOT A CONTROLLED SUBSTANCE REGISTRATION, and mapping it onto csr_required would misname the instrument and probably misdate it. Separately, the Board of Medicine''s Controlled Substance Dispensing Practitioner Registration -- seeded for WV/MD -- is by its own terms "For Physicians, Podiatric Physicians, and Physician Assistants" and does not reach APRNs, who are regulated by a different board. Whether West Virginia operates an APRN-facing state controlled-substance credential through the Board of Pharmacy under W. Va. Code ch. 60A was not established. NOT SEEDED. OPEN: West Virginia Board of Pharmacy practitioner registration. Source: https://wvrnboard.wv.gov/licensing/prescriptive-authority'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'SCHEMA GAP: THE PREREQUISITE-CREDENTIAL PROBLEM, which this group states more sharply than any earlier one. In all four of AR, KS, OK and WV an APRN licence is derivative of an RN licence, and in every one of them the two credentials have their own fee, their own application and -- in West Virginia -- their own RENEWAL YEAR. West Virginia renews RNs in even years and APRNs in odd years while providing that a lapsed RN licence lapses the APRN licence "regardless of the APRN odd-year renewal schedule"; Kansas requires APRNs to file two separate renewal applications; Arkansas and Oklahoma charge the two fees separately; and in all four states the underlying RN licence may instead be a NURSE LICENSURE COMPACT multistate licence issued by a different state entirely, on that state''s clock and at that state''s fee. The requirements table has one row per (state, license_type, field_key) and no way to say "this credential depends on that one". Every APRN fee seeded in this file is therefore the advanced credential''s fee alone and understates what the licensee pays. OPEN: model prerequisite credentials, or at minimum add a prerequisite_credential field_key.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'SCHEMA GAP: FEES ARE NOT ALWAYS SCALARS, and this group produced three more proofs. Kansas prices the same annual physician renewal at $360 on-line and $430 on paper. West Virginia prices its controlled-substance dispensing registration at $30 or $15 PER DISPENSING LOCATION depending on which alphabetical renewal cohort the physician is in. New Jersey''s APN initial certificate (group A) is $80 or $160 depending on the remaining term of the RN licence. All three are value_json. Groups A and E have now both had to bend the convention; the field_key vocabulary should permit value_json for fees explicitly rather than by exception.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'SCHEMA GAP: no anchor dates, restated for this group because four of the five states here publish fixed calendar anchors rather than offsets. Oklahoma: licence in the month of initial licensure (annual), OBN registration 31 October (annual), CME every third year. Kansas: physicians 15 May - 30 June (annual), nurses on a birth-month, birth-year-parity clock (biennial). West Virginia: physicians 30 June, A-L even years / M-Z odd years; RNs 1 May - 30 June even years; APRNs 1 May - 30 June odd years. New Jersey: physicians 30 June of odd years. Arkansas: physicians the last day of the birth month (annual), nurses a staggered biennial birth-date system with a first term of 3 to 27 months. The table stores interval LENGTHS only. Without renewal_anchor_date and csr_anchor_date the platform cannot date a single one of these duties, and the alphabetical and birth-parity cohorts cannot be expressed at all. OPEN.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-e', 1, 'unresolved',
 'METHOD NOTE, SOURCE ACCESS, GROUP E. Hosts that refused automated clients on 2026-09-18 and how each was worked around, so the next pass does not repeat the dead ends. www.ksbha.ks.gov (Kansas Board of Healing Arts) -- Akamai "Access Denied" HTTP 403 to a direct fetch with browser headers; READ successfully through a fetcher with its own egress. www.okmedicalboard.org -- HTTP 403 to a direct fetch of its HTML pages; its PDF assets fetch normally with a browser user agent, and the Board''s current Title 435 rules PDF was downloaded and read in full that way. www.obndd.ok.gov -- Akamai "Access Denied" HTTP 403 to a direct fetch (the failure the earlier pass hit); READ successfully through a fetcher, which is how Oklahoma''s csr_required, csr_fee_cents and csr_renewal_cycle_months were finally established. rules.ks.gov (Kansas Secretary of State, the official K.A.R. site) -- JavaScript single-page application, no server-rendered text, API paths return S3 AccessDenied; NOT READ, and sos.ks.gov/publications/pubs_kar.aspx returns CloudFront 403. ksbha.org (the Healing Arts Board''s legacy host, which still serves individual K.A.R. PDFs) -- expired TLS certificate and outside the direct-fetch allowlist; READ through a fetcher. oklahomarules.blob.core.windows.net (the storage behind rules.ks.gov''s Oklahoma equivalent) -- proxy 502 to a direct fetch; READ through a fetcher. www.njconsumeraffairs.gov -- Imperva/Incapsula on .aspx pages only; PDFs fetch normally. www.oscn.net (Oklahoma State Courts Network, which hosts the Oklahoma Statutes) -- robots.txt fetch failure, NOT READ, so 63 O.S. sec. 2-302 and 59 O.S. sec. 495a.1 were relied on only as quoted by the agencies'' own rules and handouts. www.nj.gov/highereducation/documents/pdf/AGMEC/BME_regulations.pdf -- a 2.6MB image-only scan with no text layer. In every case a primary alternative was sought before a gap was recorded, and NO third-party republisher (Cornell LII, Justia, regulations.justia.com, Casetext), NO CE aggregator and NO licence-service marketplace was used as a citation anywhere in this group.');

commit;
