-- =============================================================================
-- requirement_conflicts_seed_group_c.sql -- what the rules asset does NOT know
-- about IL, OH, IN, WI, MN, IA, MO, KS, NE, ND, SD, MT.
--
-- Three kinds of row live here, and all are deliberately left OPEN
-- (resolution = 'unresolved'), which blocks auto-clear (PRD 8.1 condition 6)
-- and raises RULE_UNCERTAIN (PRD 8.3):
--
--   A. GAPS -- a field_key in scope for a state/license_type for which no
--      primary source could be found and read on 2026-09-18. requirement_id is
--      NULL because no requirements row was written. published_value is NULL;
--      notes say what was searched and what remains open.
--
--   B. QUALIFIERS -- a requirements row EXISTS but a second official source, or
--      a statutory exception, narrows or contradicts it. requirement_id points
--      at the row. These are the rows that stop a confidently-wrong obligation.
--
--   C. DISAGREEMENTS -- two official sources publish different figures for the
--      same thing. The seeded value is what the licensee actually pays or does;
--      the other figure is recorded here.
--
-- observed_by is 'research-agent-group-c' throughout: these are desk-research
-- findings, not observed board behaviour.
--
-- Run AFTER requirements_seed_group_c.sql. Idempotent. Touches only rows this
-- agent owns, so it coexists with requirement_conflicts_seed.sql and with other
-- agents' state groups.
-- =============================================================================

begin;

delete from requirement_conflicts where observed_by = 'research-agent-group-c';

-- ---------------------------------------------------------------------------
-- B/C. QUALIFIERS AND DISAGREEMENTS on rows that exist.
-- ---------------------------------------------------------------------------
insert into requirement_conflicts
  (requirement_id, published_value, observed_value, observed_at, observed_by,
   occurrences, resolution, notes)
select r.id, c.published_value, c.observed_value,
       timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved', c.notes
from (values

 ('IL','MD','ce_hours_total',
  '150 hours of CME per 3-year cycle',
  'figure published in a reinstatement instruction sheet, not a renewal CE page',
  'The 150-hour figure, the 60-hour formal minimum and the 90-hour informal maximum were read from IDFPR''s Physician and Surgeon REINSTATEMENT instruction packet (https://idfpr.illinois.gov/content/dam/soi/en/web/idfpr/renewals/apply/forms/f2409.pdf and .../physician-less3-reinstatement.pdf). IDFPR''s own Continuing Education landing page publishes only the legislative topic mandates and says "Review your profession''s Act and Rules to determine any continuing education (CE) requirements that may apply". The authoritative text is 68 Ill. Adm. Code 1285.110, which could NOT be fetched: every ilga.gov URL form tried (ftp/JCAR/AdminCode, /agencies/JCAR/EntirePart, /documents/legislation/ilcs, /Legislation/ILCS/Articles) returned ROBOTS_DISALLOWED or a robots.txt TLS failure on 2026-09-18. OPEN: read 68 Ill. Adm. Code 1285.110 by hand and confirm the renewal figure equals the reinstatement figure. A reinstatement requirement is USUALLY the renewal requirement, but "usually" is not verified.'),

 ('IL','MD','renewal_cycle_months',
  '36 months (Section 1285.120, per IDFPR physician FAQ)',
  'the Department has repeatedly extended the deadline by variance',
  'IDFPR''s physician page on 2026-09-18 stated "The renewal deadline for the following licenses has been extended to August 31, 2026" for Physician and Surgeon and Licensed Physician Controlled Substance licences, and the Department publishes a dated variance document for the 2026 renewal. The underlying cycle is triennial, but the EFFECTIVE expiry date in a given cycle has been moved administratively at least once. An obligation calendar built on a fixed 36-month step from last renewal may be wrong by weeks. OPEN: decide whether the platform models board-issued deadline variances at all. Source: https://idfpr.illinois.gov/profs/physicians.html'),

 ('OH','MD','ce_topic_ethics_hours',
  '1 hour, "duty to report misconduct under section 4731.224 of the Revised Code"',
  'the field_key vocabulary has no duty-to-report slot; mapped onto ethics',
  'VOCABULARY MAPPING, NOT A VALUE DISPUTE. OAC 4731-10-02 requires one hour on a licensee''s statutory duty to report misconduct. The available topic names are opioid, ethics, implicit_bias, human_trafficking, medical_errors, domestic_violence, hiv_aids, pain_management, controlled_substance, laws_and_rules, jurisprudence_ethics, impairment and pharmacotherapeutics. Duty-to-report is arguably ethics (professional responsibility) and arguably laws_and_rules (an Ohio statutory duty). It was mapped to ce_topic_ethics_hours to match the Texas precedent, where ce_topic_ethics_hours carries "medical ethics and/or professional responsibility". OPEN: a consumer searching for an Ohio laws-and-rules obligation will not find this row. Consider a ce_topic_duty_to_report_hours key.'),

 ('OH','APRN','collaborative_agreement_required',
  'true (standard care arrangement, ORC 4723.431)',
  'ORC 4723.431 names only CNS, CNM and CNP -- not CRNAs',
  'ORC 4723.431 requires a standard care arrangement of "an advanced practice registered nurse who is designated as a clinical nurse specialist, certified nurse-midwife, or certified nurse practitioner". Certified registered nurse anesthetists are APRNs in Ohio and are NOT named in that sentence. The seeded boolean true is the conservative default and is correct for the CNP population this asset mainly serves, but it over-states the duty for a CRNA. The same subset problem is handled with value_json on the Ohio pharmacology row; it is NOT handled here because a partly-true boolean at least fails safe. OPEN: the platform needs a per-clinician APRN role attribute before this boolean can be trusted for a CRNA. Source: https://codes.ohio.gov/ohio-revised-code/section-4723.431'),

 ('IN','APRN','ce_hours_total',
  '30 contact hours, at least 8 in pharmacology',
  'applicability (all advanced practice nurses vs prescribers only) not settled',
  'Indiana PLA''s Nursing Licensing Information page states the 30/8 requirement immediately alongside the prescriptive-authority discussion, so it is not clear on the face of the page whether it binds every Indiana advanced practice nurse or only those renewing prescriptive authority. The authoritative rule is 848 IAC 5 (Prescriptive Authority for Advanced Practice Nursing). The Indiana Administrative Rules portal at https://iar.iga.in.gov/latestArticle/848/5 is a JavaScript application that serves no static rule text to an automated fetch, and https://www.in.gov/pla/professions/indiana-state-board-of-nursing/continuing-education-requirements/ and .../advanced-practice-nurse/ both returned 404 on 2026-09-18. The row is seeded as an unconditional per-cycle 30 because that is the conservative reading; if it is in fact prescriber-only it should become value_json. OPEN: read 848 IAC 5 by hand. Source: https://www.in.gov/pla/professions/nursing-home/nursing-licensing-information'),

 ('WI','MD','ce_topic_opioid_hours',
  '2 of the 30 hours on prescribing opioids and other controlled substances',
  'DSPS states the duty for "the 2025 renewal", not as a standing requirement',
  'Wisconsin DSPS''s Physician Continuing Education page says "For the 2025 renewal, each license holder will be required to take two of the required 30 hours related to prescribing opioids and other controlled substances." A statement scoped to one named renewal cannot be assumed to recur, and the 2027 and 2029 renewals are not addressed. The value is therefore carried as value_json with the board''s scope recorded rather than as a recurring per-cycle 2. The authoritative rule is Wis. Admin. Code ch. Med 13, which could NOT be fetched: docs.legis.wisconsin.gov/code/admin_code/med/13 returned ROBOTS_DISALLOWED (robots.txt ConnectTimeout, then parse failure) on repeated attempts on 2026-09-18. OPEN: read Med 13.03 by hand and establish whether the two hours recur. Source: https://dsps.wi.gov/Pages/Professions/Physician/CE.aspx'),

 ('WI','APRN','collaborative_agreement_required',
  'true (collaborative relationship with a physician or dentist, Wis. Admin. Code N 8.10(7))',
  'DSPS describes a newer APRN credential with an independent-practice pathway that ch. N 8 does not reflect',
  'TWO OFFICIAL SOURCES DESCRIBE DIFFERENT REGIMES. Wis. Admin. Code sec. N 8.10(7) -- the advanced practice nurse PRESCRIBER rule -- says "Advanced practice nurse prescribers shall work in a collaborative relationship with a physician or dentist." But DSPS''s current Advanced Practice Registered Nurse page (https://dsps.wi.gov/Pages/Professions/APNP/Default.aspx) describes an APRN credential whose applicants must "demonstrate independent practice eligibility through supervised hours", and gives a renewal window opening in 2028 -- i.e. Wisconsin has moved from APNP certification to APRN licensure with a transition-to-practice tier, and ch. N 8 has not caught up. If that tier exists, this row is a value_json case with an hours threshold, exactly like MN, NE and SD, not a bare boolean. The bill text (2023 AB 154 / SB 145) at docs.legis.wisconsin.gov was ROBOTS_DISALLOWED on 2026-09-18 and the hour threshold was NOT read, so NO number was written -- inventing one would be the precise failure this table exists to avoid. OPEN: obtain the statutory transition-to-practice hour count and the effective date, then supersede this row with version 2 carrying value_json. THIS IS THE HIGHEST-VALUE OPEN ITEM IN GROUP C.'),

 ('NE','MD','ce_cycle_months',
  '24 months',
  'the Department states the expiry and the CE total on one page but never calls the CE period a biennium',
  'Nebraska DHHS''s Medicine and Surgery page states both "Licenses expire October 1 of every even year" and that "50 hours of Category 1 AMA approved continuing education" is required for renewal, but does not say in terms that the 50 hours are measured over the two years between renewals rather than, say, annually. The 24-month CE cycle is the only reading consistent with both sentences and is seeded on that basis, but it is one inferential step and is flagged rather than hidden. OPEN: confirm against 172 NAC or obtain a written statement. Source: https://dhhs.ne.gov/licensure/pages/medicine-and-surgery.aspx'),

 ('NE','MD','ce_topic_opioid_hours',
  '3 hours on opioids, of which 0.5 on the PDMP',
  'recurrence interval not stated by the Department',
  'The Department''s Controlled Substances Continuing Competency Requirement document states the hour counts and the population ("All Professionals Who Prescribe Controlled Substances", LB 731 / Neb. Rev. Stat. sec. 38-145(6)) but does not state how often the training must be repeated. The value_json carries periodicity "per_renewal_cycle" with an explicit "periodicity_confirmed": false so a consumer cannot mistake the assumption for a finding. An obligation generator MUST NOT emit a dated duty from this row until the interval is confirmed. OPEN: obtain the interval from the Licensure Unit or from Neb. Rev. Stat. sec. 38-145. Source: https://dhhs.ne.gov/licensure/Documents/ControlledSubstancesContCompReq.pdf'),

 ('ND','MD','renewal_cycle_months',
  '24 months (Board FAQ: licences expire "on your birthday every other year")',
  'NDAC 50-02-07.1-01 prices the licence "per year"',
  'TWO OFFICIAL SOURCES USE DIFFERENT UNITS. The Board of Medicine''s Physician FAQ says licences expire "on your birthday every other year" -- biennial. NDAC ch. 50-02-07.1 says "The fee for licensure in North Dakota, whether it be by qualification, compact, locum tenens, or special license, is two hundred dollars per year" and prices late renewal at "two hundred dollars per year, up to three years, for each year past the renewal deadline". The CYCLE is not in dispute (biennial is seeded); what is unresolved is the AMOUNT a biennial renewal costs, which is why no ND fee row was written at all -- see the ND fee gap below. OPEN: obtain the biennial renewal total from the Board. Sources: https://www.ndbom.org/practitioners/physicians/faqs.asp and https://ndlegis.gov/api/acdata/pdf/50-02-07.1.pdf'),

 ('MO','APRN','collaborative_agreement_required',
  'true (written collaborative practice arrangement, sec. 334.104.2 RSMo)',
  'no hours threshold retires it -- Missouri differs structurally from MN, NE and SD',
  'RECORDED SO THE BOOLEAN IS NOT READ AS THE SAME THING AS ITS NEIGHBOURS''. Minnesota (2,080 h), Nebraska (2,000 h) and South Dakota (1,040 h) all end the APRN''s dependent-practice duty at an hours threshold, and their rows are value_json for that reason. Missouri''s is a bare true because no Missouri source publishes any threshold, and the arrangement carries live operational constraints -- a 30-mile (non-HPSA) or 50-mile (HPSA) road distance limit, two-week physician review, annual review of the agreement, and physician review of at least 20% of controlled-substance cases -- that persist for the whole of the APRN''s career. A consumer must not normalise this to the tiered states'' shape. OPEN: confirm there is genuinely no threshold in RSMo ch. 334 or ch. 335; revisor.mo.gov refused automated access on 2026-09-18 ("appears a bot-like access pattern was detected"). Sources: https://pr.mo.gov/nursing-advanced-practice-nursing-collaborative.asp and https://www.sos.mo.gov/cmsimages/adrules/csr/current/20csr/20c2200-4.pdf'),

 ('MT','MD','ce_hours_total',
  '0 (Board: "Montana does not require Physicians to acquire CME")',
  'a zero is a real assertion and must not be silently treated as "unknown"',
  'NOT A DISPUTE -- A CONSUMER WARNING. Montana is the only state in Group C where a zero CE requirement is affirmatively published rather than merely absent, for both MD and APRN. A consumer that treats value_num = 0 as falsy and falls back to a default, or that treats the absence of a ce_cycle_months row as "unknown cycle" and suppresses the zero, will show a Montana physician an unknown CME status instead of the correct answer, which is none. No ce_cycle_months row is written for MT/MD or MT/APRN because a period for a zero requirement is meaningless. Source: https://boards.bsd.dli.mt.gov/medical-examiners/faq and https://boards.bsd.dli.mt.gov/nursing/continuing-education')

) as c(state, license_type, field_key, published_value, observed_value, notes)
join requirements r
  on r.state = c.state
 and r.license_type = c.license_type
 and r.field_key = c.field_key
 and r.is_current
 and r.deleted_at is null
 and r.verified_by = 'research-agent-group-c';

-- ---------------------------------------------------------------------------
-- A. GAPS -- in-scope field_keys with no verified value. requirement_id NULL.
-- ---------------------------------------------------------------------------
insert into requirement_conflicts
  (requirement_id, published_value, observed_value, observed_at, observed_by,
   occurrences, resolution, notes)
values

-- ---- ILLINOIS -------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IL/MD/csr_required, IL/MD/csr_fee_cents, IL/MD/csr_renewal_cycle_months and the same three for IL/APRN. Illinois DOES issue a state controlled substances registration -- IDFPR''s physician page names "Licensed Physician Controlled Substance licenses" as a distinct credential it renews (https://idfpr.illinois.gov/profs/physicians.html), the physician reinstatement packet quotes controlled substances registration fees of "$5" for a new registration and "$15" for reinstatement, and the APRN CE FAQ speaks of "prescribers with Controlled Substances Registrations". But NO source read on 2026-09-18 states in terms that a prescriber MUST hold it, and the $5/$15 figures appear only in a reinstatement instruction sheet, not a fee schedule. A required-ness cannot be asserted from the existence of a credential, and a fee cannot be asserted from a reinstatement packet. NOT SEEDED -- neither the boolean nor the fee. OPEN: read the Illinois Controlled Substances Act (720 ILCS 570) sec. 302 and the IDFPR fee rule. This is a real recurring obligation the table currently does not carry for Illinois.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IL/APRN/collaborative_agreement_required and IL/APRN/supervision_required. Illinois runs a TWO-TIER APRN regime -- an ordinary APRN and a Full Practice Authority APRN (FPA-APRN), the two appearing side by side throughout IDFPR''s own CE FAQ. The instrument for the ordinary tier is a written collaborative agreement under the Nurse Practice Act (225 ILCS 65) and the FPA tier retires it after a practice-hour threshold. NEITHER THE INSTRUMENT NOR THE THRESHOLD WAS VERIFIED: IDFPR''s APRN/FPA instruction sheet at .../renewals/apply/forms/aprn-fpa.pdf returned 404 on 2026-08-18, and 68 Ill. Adm. Code 1300.465 (Full Practice Authority) and 225 ILCS 65/65-43 are on ilga.gov, which returned ROBOTS_DISALLOWED for every URL form tried. NOT SEEDED. Writing a bare true here would misstate the duty for every Illinois FPA-APRN, and writing false would misstate it for everyone else. OPEN: read 68 Ill. Adm. Code 1300.465 and 225 ILCS 65/65-43 by hand; the result is a value_json row carrying the hours threshold, not a boolean.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IL/MD/renewal_fee_cents, IL/APRN/renewal_fee_cents and IL/APRN/initial_license_fee_cents. IDFPR publishes physician and APRN fees in 68 Ill. Adm. Code 1285 and 1300 rather than on a web fee schedule, and both are on ilga.gov (ROBOTS_DISALLOWED throughout 2026-09-18). The physician reinstatement packet directs applicants to an interactive "Restoration/Reinstatement Fee Calculator" rather than printing amounts. Only IL/MD/initial_license_fee_cents ($500, from the physician licensing FAQ) could be verified. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IL/MD and IL/APRN renewal_window_days, fingerprint_required. IDFPR''s License Renewal Information page (https://idfpr.illinois.gov/dpr/license-renewal-info.html) serves its expiry-date table from JavaScript ("Large data table content is loading...") and returns no static rows to an automated fetch. No IDFPR page read states either that fingerprints are required or that they are not, for medicine or for nursing. A negative cannot be asserted from silence. NOT SEEDED.'),

-- ---- OHIO -----------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP OH/APRN/initial_license_fee_cents and OH/APRN/renewal_fee_cents. ORC sec. 4723.08 was read in full and gives $150 for an APRN licensure application and $135 for an APRN renewal -- but its own operative words are "The board of nursing MAY IMPOSE FEES NOT TO EXCEED the following limits". A statutory CAP is not the amount the licensee pays, and this seed''s fee convention is the amount actually paid. The Ohio Board of Nursing''s fee page (https://nursing.ohio.gov/page/rQSHYkYXmAGGAYIgT4jPz) and its APRN practice page are JavaScript applications that returned navigation chrome and no fee content on 2026-09-18. NOT SEEDED. Note the contrast: the Ohio MD fees ARE seeded because the State Medical Board publishes "$305.00" as the charged amount on its own physician page. OPEN: obtain the Board of Nursing''s charged fee schedule.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP OH/MD/csr_required and OH/APRN/csr_required. No State Medical Board of Ohio or Ohio Board of Nursing page read on 2026-09-18 states either that Ohio issues a separate state controlled substance registration for prescribers or that it does not. Ohio''s Board of Pharmacy licenses Terminal Distributors of Dangerous Drugs, which is a different instrument attached to a location rather than to a prescriber, and no page was read that settles the prescriber question. A negative cannot be asserted from silence. NOT SEEDED. OPEN: read ORC ch. 3719 and the Board of Pharmacy''s prescriber guidance.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP OH/MD and OH/APRN renewal_window_days. Neither board publishes the date on which the renewal transaction opens. ORC sec. 4723.24 gives nursing DEADLINES ("An application for renewal of the license is due on the fifteenth day of September of the renewal year"; the licence "lapses on the first day of November of the renewal year") but a deadline and a lapse date are not a window-open date. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP OH/APRN/fingerprint_required and OH/APRN/supervision_required. No Ohio Board of Nursing page read states a fingerprint condition for APRNs. On supervision: ORC 4723.431 requires COLLABORATION via a standard care arrangement and that is what was seeded; nothing read asserts physician SUPERVISION of an Ohio APRN, and the absence of a supervision statement is not a verified "no supervision". NOT SEEDED -- deliberately, because collapsing collaboration into supervision (or writing supervision_required = false from the collaboration rule) would destroy exactly the distinction this asset sells.'),

-- ---- INDIANA --------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IN/MD/ce_hours_total and IN/MD/ce_cycle_months. Three Indiana PLA sources were read end to end -- the Physicians Licensing Information page, the Top Ten FAQs for Physician License Renewals, and the Generic MD/DO Active Renewal Form -- and NONE of them states a continuing medical education hour requirement or carries a CME attestation. Indiana is widely understood to impose no general CME mandate on physicians, but WIDELY UNDERSTOOD IS NOT VERIFIED, and unlike Montana no Indiana source publishes the negative in terms. A zero is therefore NOT seeded; Montana''s zero is seeded because the Montana board writes "Montana does not require Physicians to acquire CME", and Indiana''s boards write nothing at all. OPEN: obtain a written statement from the Medical Licensing Board, or read IC 25-22.5-2-7 and 844 IAC 5.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IN/MD/csr_renewal_cycle_months and IN/APRN/csr_renewal_cycle_months. Indiana''s CSR is verified to exist and to be mandatory, and its $60 fee is verified. The PLA page says only that "Each registrant will receive renewal information for their CSR at the same time that he or she receives renewal information for his or her professional license" and that "The Renewal Notice is sent no later than 90 days prior to the expiration" -- which STRONGLY SUGGESTS the CSR runs on the same biennial clock as the underlying licence but does not state a period. A CSR expiry generated from the licence expiry would be an inference, and a wrong CSR date stops a prescriber writing. NOT SEEDED. OPEN: read 856 IAC 2 or obtain the CSR expiry rule. Source: https://www.in.gov/pla/professions/controlled-substance-registration'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IN/APRN/renewal_cycle_months, IN/APRN/renewal_fee_cents, IN/APRN/initial_license_fee_cents and IN/APRN/ce_cycle_months. Indiana PLA''s Nursing Licensing Information page publishes the RN figures -- "Registered Nurse (RN) licenses expire on October 31st of every odd-numbered year", $50 renewal, $50 application -- but says nothing about the expiry date or fee of the APRN / prescriptive authority credential itself, and the two PLA pages that would (.../continuing-education-requirements/ and .../advanced-practice-nurse/) both returned 404 on 2026-09-18. An Indiana APN holds an RN licence, so the RN dates are LIKELY to govern, but carrying a figure from one licence type to another is precisely the inference this standard forbids. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IN/MD/fingerprint_required, IN/APRN/fingerprint_required, IN/MD/renewal_window_days, IN/APRN/renewal_window_days, IN/APRN/supervision_required. Nothing read on 2026-09-18 addresses fingerprinting for either Indiana profession. On the window: the CSR page gives a 90-day NOTICE period, which is a notice date and not a transaction-open date, and no licence-renewal window was published. On supervision: Indiana''s instrument is a written practice / collaborative agreement, which was seeded; no source asserts supervision, and silence is not a "no". NOT SEEDED.'),

-- ---- WISCONSIN ------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'ACCESS GAP WISCONSIN ADMINISTRATIVE CODE. docs.legis.wisconsin.gov refused automated fetch throughout 2026-09-18: chapter Med 13 (physician CE) returned ROBOTS_DISALLOWED twice, once on a robots.txt ConnectTimeout and once on a parse failure, and the 2023 AB 154 / SB 145 bill texts did the same. Wisconsin Admin Code ch. N 8 WAS retrieved, but only because DSPS serves it as a PDF at a different path. CONSEQUENCE: the Wisconsin physician CE total (30 hours) and biennium rest on DSPS web pages and the #570 application information sheet rather than on Med 13 itself, and the opioid hours could not be confirmed as recurring. OPEN: retrieve Med 13 by hand.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP WI/APRN/ce_hours_total. Wis. Admin. Code sec. N 8.05(1) imposes 16 contact hours per biennium IN CLINICAL PHARMACOLOGY OR THERAPEUTICS specifically, including 2 in responsible prescribing of controlled substances. It does NOT state a general continuing education total for the credential, and a topic requirement is not a total. Seeding 16 as ce_hours_total would misrepresent a pharmacology-only duty as the whole CE obligation. NOT SEEDED; the 16 is recorded under ce_topic_pharmacotherapeutics_hours where it belongs. OPEN: establish whether Wisconsin imposes any general APRN CE total, particularly under the new APRN licensure regime.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP WI/MD/initial_license_fee_cents, WI/APRN/initial_license_fee_cents, WI/MD/fingerprint_required, WI/APRN/fingerprint_required, WI/MD/renewal_window_days, WI/APRN/renewal_window_days, WI/MD/csr_required, WI/APRN/csr_required. DSPS''s Renewal Dates and Fees schedule carries RENEWAL fees only; the initial credential fee is in a separate schedule that was not located. Wisconsin''s #570 Medicine and Surgery Application Information sheet gives only an oral examination fee ($266). Nothing read addresses fingerprinting, a renewal-window open date, or a Wisconsin state controlled substance registration for either profession. NOT SEEDED.'),

-- ---- MINNESOTA ------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MN/MD/initial_license_fee_cents and MN/MD/renewal_fee_cents. The Minnesota Board of Medical Practice''s Renew Your License page describes the annual renewal process but prints no amount, and the Board''s fees page at https://mn.gov/boards/medical-practice/licensing/fees/ returned 404 on 2026-09-18. NOT SEEDED. Note this is the ONLY missing piece for MN/MD -- the annual cycle and the three-year 75-hour CME clock are both verified, and they are the two numbers most often conflated for this state.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MN/APRN/ce_hours_total and MN/APRN/ce_cycle_months. The Minnesota Board of Nursing''s Continuing Education page states "During a typical continuing education participation period (24 months) an RN must participate in 24 contact hours of continuing education" -- but the page addresses RN and LPN renewal and states no APRN figure. A Minnesota APRN holds an RN licence and so is very likely bound by the 24 hours, but carrying a figure from the RN licence to the APRN licence is an inference across license_types and is exactly what this standard forbids. NOT SEEDED. OPEN: read Minn. R. ch. 6310 for the APRN-specific requirement, or obtain a Board statement. Source: https://mn.gov/boards/nursing/licensure/continuing-ed/'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MN/APRN/supervision_required. Minnesota''s verified instrument is a COLLABORATIVE AGREEMENT ending at 2,080 hours, which is seeded as value_json under collaborative_agreement_required. No Minnesota source read asserts physician SUPERVISION of an APRN, and none asserts its absence. A false here would look like a finding; it would be an inference from the presence of a different instrument. NOT SEEDED. This is the distinction the brief calls commercially important and it is preserved deliberately: Minnesota has a collaboration tier, Nebraska has a supervision tier, and the two rows in this seed use different field_keys for that reason.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MN/MD and MN/APRN renewal_window_days, fingerprint_required, csr_required. Nothing read for either Minnesota board states a renewal-window open date, a fingerprint condition, or whether Minnesota issues a state controlled substance registration. NOT SEEDED.'),

-- ---- IOWA -----------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IA/MD/ce_topic_abuse_reporter_hours -- AND A VOCABULARY GAP. Iowa DIAL states that physicians in certain specialties must, at audit, submit "a copy of the certificate showing completion of the training within the last five years" for abuse identification and reporting. A FIVE-YEAR RECURRING TRAINING IS VERIFIED; the HOUR COUNT IS NOT, and the permitted topic names (opioid, ethics, implicit_bias, human_trafficking, medical_errors, domestic_violence, hiv_aids, pain_management, controlled_substance, laws_and_rules, jurisprudence_ethics, impairment, pharmacotherapeutics) contain no abuse-reporter slot. domestic_violence is the nearest name and is NOT the same subject -- Iowa''s duty is mandatory-reporter training for child and dependent adult abuse. NOT SEEDED under any key. OPEN: read IAC 481 ch. 654 for the hour count and add a ce_topic_mandatory_reporter_hours key. Source: https://dial.iowa.gov/licenses/health-professions/physicians/continuing-education-physicians'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'QUALIFIER ON THE IOWA END-OF-LIFE ROW: it is seeded under ce_topic_pain_management_hours because the vocabulary has no end-of-life-care name, and its value_json carries "topic": "end-of-life care" so the mismatch is visible in the data rather than only here. Iowa has TWO separate five-year topic duties -- two hours on the CDC opioid-prescribing guideline (seeded under ce_topic_opioid_hours) and two hours on end-of-life care (seeded under ce_topic_pain_management_hours) -- with different trigger populations. A consumer that reads only the key names will think Iowa has a pain-management requirement it does not have. OPEN: add a ce_topic_end_of_life_hours key. Source: https://dial.iowa.gov/chronic-pain-and-end-life-training'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IA/APRN/supervision_required and IA/APRN/collaborative_agreement_required. Iowa Administrative Code 655 ch. 7 was read in full and states "An ARNP licensed by the board may prescribe, administer, or dispense prescription drugs or devices, including controlled substances, within the ARNP''s role and population foci" -- with no collaboration or supervision condition attached. The chapter defines "collaboration" but requires it only in the fluoroscopy-supervision context. IOWA IS ALMOST CERTAINLY A FULL-PRACTICE-AUTHORITY STATE, and a false on both keys would probably be right -- but the board asserts the POSITIVE grant, not the negative of a requirement, and this table does not convert an absence into a false. NOT SEEDED. OPEN: obtain an affirmative DIAL or Board statement that no collaborative agreement is required, then seed both as false. THIS IS A HIGH-VALUE, LOW-EFFORT OPEN ITEM. Source: https://www.legis.iowa.gov/docs/iac/chapter/05-28-2025.655.7.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IA/MD/renewal_fee_cents, IA/MD/initial_license_fee_cents, IA/APRN/initial_license_fee_cents. IAC 481--652.12(147,148) prices physician renewal only by cross-reference -- fees are "specified in 481--subparagraph 651.4(1)''c''(1)" -- and that subparagraph was not retrieved. DIAL''s nursing renewals page gives the $99 nursing renewal (seeded) but no initial ARNP fee. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP IA/MD/renewal_window_days, IA/MD/fingerprint_required, IA/APRN/fingerprint_required, IA/MD/csr_required, IA/APRN/csr_required. Nothing read states an Iowa physician renewal-window open date (the 60-day figure that IS seeded is from IAC 655 ch. 7 and is ARNP-specific -- it must NOT be applied to physicians), a fingerprint condition for either profession, or whether Iowa issues a state controlled substance registration. NOT SEEDED.'),

-- ---- MISSOURI -------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MO/MD/renewal_cycle_months -- THE SINGLE MOST CONSEQUENTIAL MISSING VALUE IN GROUP C. Missouri''s physician CME is verified at 50 hours over a FIXED 24-month calendar window ("beginning January 1 of each even-numbered year and ending December 31 of each odd-numbered year", 20 CSR 2150-2.125), and the fee rule 20 CSR 2150-2.080 gives a single "Renewal Fee $147" without stating a period. THE CME PERIOD IS NOT NECESSARILY THE LICENCE PERIOD, and in this very group Minnesota proves they can differ by a factor of three. RSMo 334.075 was read and addresses only the CE condition on renewal, not the frequency; revisor.mo.gov then refused further automated access ("appears a bot-like access pattern was detected") so RSMo 334.071 could not be read, and pr.mo.gov''s Healing Arts and Physicians and Surgeons pages publish MOPRO account guidance rather than the renewal cycle. NOT SEEDED. Deriving 24 months from the CME window would be the exact failure mode this asset exists to prevent. OPEN: read RSMo 334.071 and 20 CSR 2150-2.010 by hand.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'VOCABULARY GAP MO/MD nutrition CME. 20 CSR 2150-2.125 requires that "A total of at least one (1) hour, within the required fifty (50) hours, must pertain to the topic of the health benefits of nutrition." This is a real, recurring, unconditional per-cycle Missouri duty and there is NO permitted topic name that fits it -- it is not ethics, not laws_and_rules, not pain_management, not any of the thirteen. NOT SEEDED under any key rather than mislabelled under a wrong one. OPEN: add a ce_topic_nutrition_hours key. Source: https://www.sos.mo.gov/cmsimages/adrules/csr/current/20csr/20c2150-2.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MO/APRN/initial_license_fee_cents, MO/APRN/renewal_fee_cents, MO/APRN/ce_cycle_months, MO/MD/ce_topic_* generally, and MO/MD and MO/APRN renewal_window_days, fingerprint_required, csr_required. 20 CSR 2200-4 gives the nursing renewal DATES (RN and APRN April 30 of each odd-numbered year) but the fee rule for nursing was not retrieved. The MO/APRN ce_hours_total row is value_json and applies only to uncertified APRNs, so no unconditional ce_cycle_months is written for it. Nothing read addresses fingerprinting, a renewal-window open date, or a Missouri state controlled substance registration. NOT SEEDED.'),

-- ---- KANSAS ---------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'KANSAS IS THE SPARSEST STATE IN GROUP C AND DELIBERATELY SO. GAP KS/MD for EVERY field_key: renewal_cycle_months, renewal_window_days, ce_hours_total, ce_cycle_months, every ce_topic key, initial_license_fee_cents, renewal_fee_cents, fingerprint_required, csr_required. Four Kansas Board of Healing Arts pages were read on 2026-09-18 -- Renewal Dates, the Doctor of Medicine and Surgery licensing FAQ, the Doctor of Medicine and Surgery licence-type page, and the General Counsel Healing Arts FAQ -- and NONE of them publishes an hour count, a fee, or a cycle length. The Renewal Dates page gives a renewal PERIOD of "May 15 - July 31" for "MD, MD Resident Active" with late renewal "July 1 - July 31"; that is a pair of calendar dates, not a cycle length and not a window in days, and converting it would be invented precision. K.S.A. 65-2809 was read in full and expressly delegates all of it: "The license shall be canceled on the date established by rules and regulations of the board" and "The requirements for continuing education for licensees of each branch of the healing arts shall be established by rules and regulations adopted by the board." The operative K.A.R. 100-15 series is not served in retrievable form from ksbha.ks.gov or ksrevisor.gov. NOT ONE KS/MD ROW IS SEEDED. An honestly empty Kansas is the correct deliverable; a Kansas populated from Nebraska or Missouri would be a defect. OPEN: obtain K.A.R. 100-15-4, 100-15-5 and the Board fee regulation, by hand or by request to the Board.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP KS/APRN for every field_key except renewal_cycle_months. K.S.A. 65-1132 was read and establishes the two-year APRN licence period (seeded) and that renewal requires "evidence of completion of continuing education in the advanced practice registered nurse role" -- BUT IT PUBLISHES NO HOUR COUNT and expressly leaves the standard to "the board or approved national organizations", and it requires "the prescribed biennial renewal fee" without an amount. K.S.A. 65-1131 was also read and, contrary to expectation, contains no APRN protocol or collaboration requirement in the text served. Kansas APRN prescribing is understood to run on a written protocol with a responsible physician under K.S.A. 65-1130, but that section returned ROBOTS_DISALLOWED on ksrevisor.gov on 2026-09-18 and WAS NOT READ. NEITHER collaborative_agreement_required NOR supervision_required IS SEEDED FOR KANSAS. Given that this group contains both full-practice-authority and protocol states, guessing Kansas from its neighbours would be the single most likely way to get an NP practice-authority row wrong. OPEN: read K.S.A. 65-1130 and K.A.R. 60-11.'),

-- ---- NEBRASKA -------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP NE/MD/initial_license_fee_cents, NE/MD/renewal_fee_cents, NE/APRN/renewal_fee_cents. Nebraska DHHS''s Medicine and Surgery page points at "Title 172 NAC 2" for the fee schedule without printing amounts, and the Nurse Licensing Renewal page says only that nurses must "pay the renewal fee". 172 NAC 2 was not retrieved. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP NE/APRN/initial_license_fee_cents -- AND A GENUINE DISAGREEMENT INSIDE ONE DOCUMENT. The Department''s APRN-Nurse Practitioner application information publishes TWO application fees, "$68.00" and "$25.00", selected by the month in which the licence will be issued, because an initial Nebraska licence runs "anywhere from 1 day to 24 months" to the next October 31 even-year expiry and the fee is prorated. THERE IS NO SINGLE AMOUNT THE APPLICANT PAYS, so no scalar can be seeded without being wrong for roughly half of applicants. NOT SEEDED. OPEN: the schema has no shape for a proration table; consider value_json on fee keys. Source: https://dhhs.ne.gov/licensure/Documents/APRNNPapp.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP NE/APRN/collaborative_agreement_required. Nebraska''s verified instrument is a TRANSITION TO PRACTICE agreement with a SUPERVISING PROVIDER, ending at 2,000 hours, and it is seeded under supervision_required using the Department''s own word. Nothing read states that Nebraska additionally or alternatively requires a COLLABORATIVE agreement, and nothing states that it does not. Writing false here would look like a finding. NOT SEEDED.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP NE/MD and NE/APRN renewal_window_days, fingerprint_required, csr_required, and NE/APRN ce_cycle_months. Nebraska publishes fixed expiry dates (October 1 even years for medicine, October 31 even years for nursing) but no window-open date. Nothing read addresses fingerprinting or a Nebraska state controlled substance registration. The NE/APRN CE row is value_json with conditional pathways, so no unconditional CE cycle is written for it. NOT SEEDED.'),

-- ---- NORTH DAKOTA ---------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP ND/MD/initial_license_fee_cents and ND/MD/renewal_fee_cents. See the qualifier row on ND/MD/renewal_cycle_months: NDAC 50-02-07.1-01 prices North Dakota licensure at "two hundred dollars per year" while the Board''s FAQ says licences expire "on your birthday every other year". $200 and $400 are both defensible readings of a biennial renewal and the Board publishes neither as the charged amount. NO ND FEE ROW IS WRITTEN AT ALL, in either direction. OPEN: obtain the charged biennial amount from the Board. Sources: https://ndlegis.gov/api/acdata/pdf/50-02-07.1.pdf and https://www.ndbom.org/practitioners/physicians/faqs.asp'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP ND/APRN/supervision_required and ND/APRN/collaborative_agreement_required. Both NDAC ch. 54-05-03.1 (Advanced Practice Registered Nurse) and NDCC ch. 43-12.1 (Nurse Practices Act) were read IN FULL on 2026-09-18 and NEITHER contains any requirement that an APRN collaborate with, be supervised by, or hold an agreement with a physician; 54-05-03.1-02 licenses the APRN on "express authority of the board" and the Act defines prescriptive practice without attaching physician oversight. NORTH DAKOTA IS ALMOST CERTAINLY A FULL-PRACTICE-AUTHORITY STATE. A false on both keys would probably be right -- but two chapters containing no such requirement is an absence, not a board assertion, and this table does not convert absence into a verified false. NOT SEEDED. OPEN: obtain an affirmative ND Board of Nursing statement of full practice authority, then seed both false. HIGH-VALUE, LOW-EFFORT. Sources: https://ndlegis.gov/information/acdata/pdf/54-05-03.1.pdf and https://ndlegis.gov/cencode/t43c12-1.pdf'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP ND/APRN/renewal_fee_cents, ND/APRN/initial_license_fee_cents, ND/APRN/fingerprint_required, ND/MD/renewal_window_days, ND/APRN/renewal_window_days, ND/MD/csr_required, ND/APRN/csr_required. The ND Board of Nursing''s renewal FAQ and CE pages carry no fee amounts and direct enquiries to renewal@ndbon.org. The ND Board of Medicine sends renewal NOTICES 59 and 14 days before expiry, which is a notice schedule, not a transaction-open date. Nothing read addresses a North Dakota state controlled substance registration. NOT SEEDED. Note ND/APRN has a further unseeded practice condition the schema cannot hold: 400 hours of nursing practice in the preceding four years.'),

-- ---- SOUTH DAKOTA ---------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP SD/MD/ce_hours_total and SD/MD/ce_cycle_months. The whole of ARSD art. 20:47 (Board of Medical and Osteopathic Examiners) was retrieved and read on 2026-09-18 -- application procedure, fees, ethical standards, controlled-substance record documentation -- and it contains NO continuing medical education requirement of any kind. South Dakota is widely understood to impose no CME mandate on physicians. That is an absence in the rules, NOT a published negative: contrast Montana, whose board writes "Montana does not require Physicians to acquire CME" and whose zero IS seeded. A zero is a real assertion and is not written from a board''s silence. NOT SEEDED. OPEN: obtain a written statement from the Board, or read SDCL ch. 36-4 and ARSD art. 20:78, then seed the zero. Source: https://sdlegislature.gov/api/Rules/Rule/20:47.html?all=true'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP SD/APRN/renewal_fee_cents and SD/APRN/ce_hours_total. ARSD ch. 20:48:06 was retrieved and prices the biennial renewal of an RN licence at ninety-five dollars plus a ten-dollar nurses'' education assistance scholarship levy (SDCL 36-9-77) and a ten-dollar nursing workforce centre levy (SDCL 36-9-95) -- $115 in total -- and prices CRNA and clinical nurse specialist renewals at ninety-five dollars, but it contains NO certified nurse practitioner renewal fee. The RN figure must not be carried across: this seed''s SD/APRN rows describe the CNP credential. ARSD ch. 20:48:12, which the chapter index still lists as the continuing education chapter, was "Repealed. 7 SDR 41, effective November 3, 1980" and ARSD ch. 20:48:03 imposes practice-hour conditions rather than CE hours. NOT SEEDED. OPEN: locate the current CNP fee and any CE rule.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP SD/MD and SD/APRN fingerprint_required, csr_required; SD/APRN renewal_window_days; SD/MD initial and renewal CE topic keys. Nothing read addresses fingerprinting for either South Dakota profession or a South Dakota state controlled substance registration. The 90-day renewal window that IS seeded comes from ARSD 20:47:03:13 and is MEDICAL BOARD specific -- it must NOT be applied to the Board of Nursing. NOT SEEDED.'),

-- ---- MONTANA --------------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MT/APRN/supervision_required, MT/APRN/collaborative_agreement_required and MT/APRN/ce_topic_pharmacotherapeutics_hours. Montana is understood to be a full-practice-authority state, but the Board of Nursing''s APRN page carries the practice-authority and prescriptive-authority material behind a separate link that returned 404 on 2026-09-18 (.../nursing/license-information/aprn/prescriptive-authority), and ARM 24.159 was not retrieved -- rules.mt.gov returned HTTP 405 to an automated fetch and the Board of Medical Examiners'' rules PDF covers only ch. 24.156, which has no APRN jurisdiction. NEITHER PRACTICE-AUTHORITY KEY IS SEEDED. NOT SEEDED. OPEN: read ARM 24.159 subchapter 14 and MCA 37-8-202.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'GAP MT/APRN/initial_license_fee_cents, MT/MD/renewal_window_days, MT/APRN/renewal_window_days, MT/MD/fingerprint_required, MT/APRN/fingerprint_required, MT/MD/csr_required, MT/APRN/csr_required. On the window: the Board of Medical Examiners states physicians renew "between Feb. 1 and March 31 of their renewal year", which is a pair of calendar dates; deriving 59 days from them would be computed precision the Board does not publish. Nothing read addresses fingerprinting or a Montana state controlled substance registration for either profession. NOT SEEDED.'),

-- ---- CROSS-CUTTING --------------------------------------------------------
(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'SCOPE GAP: license_type ''DO'' is NOT COVERED in any of the twelve Group C states. In OH, IN, WI, MN, IA, NE, ND, SD and MT a single authority licenses MDs and DOs -- the State Medical Board of Ohio names "Physicians (MD, DO, DPM)" on the very page the Ohio fees were read from, Indiana''s PLA FAQ covers "Medical Doctor (MD) and Doctor of Osteopathic Medicine (DO)" together, the Wisconsin DSPS fee schedule prints identical 10/31-odd-year $120 lines for MD and DO, and the South Dakota board is the Board of Medical AND OSTEOPATHIC Examiners. The MD rows are therefore LIKELY to hold for DOs in those states, but "likely" is not verified and no DO-specific page was read. ILLINOIS, KANSAS AND MISSOURI ARE DIFFERENT AND MORE DANGEROUS: Missouri''s osteopathic licensure sits in its own part of 20 CSR 2150 and Kansas and Illinois regulate osteopathy under separate provisions of the healing-arts and medical practice acts. A consumer that resolves a DO to the MD rows is producing an unverified obligation.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'SCHEMA GAP, GROUP C RESTATEMENT: the field_key set still has no slot for the PERIODICITY of a mandated CE topic, and Group C makes it worse than the first four states did. Iowa runs TWO five-year topic clocks (CDC opioid guideline; end-of-life care) on top of a two-year licence. Minnesota runs a THREE-year CME clock on top of an ANNUAL licence -- the widest divergence in the table, and the one most likely to be silently mis-scheduled. Wisconsin scopes its opioid hours to a single named renewal. Nebraska publishes an opioid hour count with NO interval at all. Every one of these is carried as value_json with an explicit periodicity, and Nebraska''s additionally carries "periodicity_confirmed": false. ANY CONSUMER THAT READS value_num AND IGNORES value_json WILL SILENTLY DROP THESE REQUIREMENTS, and any consumer that anchors a topic clock to renewal_cycle_months will produce wrong dates for IA, MN and NY alike. Resolving this means a schema change, not a data change.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'SCHEMA GAP, NP PRACTICE AUTHORITY: four of the twelve Group C states grant independent NP practice only after a transition-to-practice threshold, and they disagree on BOTH the number and the instrument -- Minnesota 2,080 hours under a COLLABORATIVE agreement (CNP and CNS only; CNMs and CRNAs exempt), Nebraska 2,000 hours under a written TRANSITION TO PRACTICE agreement with a SUPERVISING provider, South Dakota 1,040 hours under a COLLABORATIVE agreement retired on Form 3, and Wisconsin an unread threshold under its new APRN licensure. Missouri and Indiana require a collaborative/written practice agreement with NO threshold at all, and Ohio requires a standard care arrangement with no threshold. All four thresholds are carried in value_json and the instrument distinction is carried by using supervision_required for Nebraska and collaborative_agreement_required for the others; NEITHER IS COLLAPSED INTO THE OTHER ANYWHERE IN THIS FILE. What the schema still cannot express is that the SAME clinician crosses the threshold mid-cycle: the platform holds no per-clinician cumulative-practice-hours attribute, so no consumer can currently decide which side of a threshold a given NP is on. Until it does, every one of these rows is un-actionable per-clinician and should raise RULE_UNCERTAIN rather than generate an obligation.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'SCHEMA/VOCABULARY GAP, GROUP C: five verified, recurring, board-published CE duties in these twelve states have NO home in the permitted topic vocabulary and are therefore absent from the requirements table entirely -- Ohio''s 1-hour duty-to-report-misconduct CME (seeded under ce_topic_ethics_hours as the nearest fit, and flagged), Missouri''s 1-hour health-benefits-of-nutrition CME, Iowa''s five-yearly end-of-life care training (seeded under ce_topic_pain_management_hours as the nearest fit, and flagged), Iowa''s five-yearly abuse-identification and mandatory-reporter training, and Illinois''s 1-hour Alzheimer''s disease and other dementias CME for both MDs and APRNs treating patients aged 26 and over (a conditional-population requirement published on IDFPR''s Continuing Education page and in the physician and APRN packets). The Illinois sexual-harassment-prevention hour, required of both professions every cycle, is likewise unmappable. THESE ARE REAL OBLIGATIONS A CLIENT WILL BE AUDITED ON. Adding ce_topic_nutrition_hours, ce_topic_dementia_hours, ce_topic_sexual_harassment_hours, ce_topic_end_of_life_hours and ce_topic_mandatory_reporter_hours would close it; inventing them unilaterally in a data seed would not.'),

(null, null, null, timestamptz '2026-09-18 00:00:00+00', 'research-agent-group-c', 1, 'unresolved',
 'ACCESS GAP, GROUP C SUMMARY -- the sources that could NOT be read on 2026-09-18, and which therefore account for most of the empty cells above. ROBOTS/TLS REFUSAL: ilga.gov in every URL form tried (Illinois Medical Practice Act, Nurse Practice Act, and all of 68 Ill. Adm. Code 1285 and 1300); docs.legis.wisconsin.gov (Wis. Admin. Code ch. Med 13, and 2023 AB 154 / SB 145); ksrevisor.gov K.S.A. 65-1130; rules.mt.gov (HTTP 405 on ARM 24.156.2718). BOT BLOCKING: revisor.mo.gov after two requests ("appears a bot-like access pattern was detected"), which is why the Missouri physician renewal cycle is unseeded. JAVASCRIPT-ONLY PORTALS serving no static text: iar.iga.in.gov (848 IAC 5, Indiana APRN prescriptive authority); nursing.ohio.gov (Board of Nursing fee schedule and APRN practice pages); idfpr.illinois.gov/dpr/license-renewal-info.html (the expiry-date table); sdlegislature.gov''s HTML rule and statute viewers, though its /api/Rules/Rule/<article>.html?all=true endpoint DID work and is how the South Dakota rows were obtained. DEAD LINKS: idfpr.illinois.gov .../aprn-fpa.pdf, in.gov/pla .../continuing-education-requirements/ and .../advanced-practice-nurse/, mn.gov/boards/medical-practice/licensing/fees/, boards.bsd.dli.mt.gov .../aprn/prescriptive-authority -- all 404. Every one of these is retrievable by hand or by a request to the board; none of them was guessed around.');

commit;
